// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalaryCalculator.Infrastructure.Data;

#nullable disable

namespace SalaryCalculator.Infrastructure.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20240626185117_Initial Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("SalaryCalculator.Infrastructure.Entities.IncomeTaxRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ChargeableIncome")
                        .HasColumnType("REAL");

                    b.Property<double?>("CumulativeIncome")
                        .HasColumnType("REAL");

                    b.Property<double?>("CumulativeTax")
                        .HasColumnType("REAL");

                    b.Property<double?>("Rate")
                        .HasColumnType("REAL");

                    b.Property<double?>("TaxPayable")
                        .HasColumnType("REAL");

                    b.Property<string>("Year")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("IncomeTaxRates");
                });

            modelBuilder.Entity("SalaryCalculator.Infrastructure.Entities.Pension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("EmployeeRate")
                        .HasColumnType("REAL");

                    b.Property<double?>("EmployerRate")
                        .HasColumnType("REAL");

                    b.Property<string>("TierName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pensions");
                });

            modelBuilder.Entity("SalaryCalculator.Infrastructure.Entities.Salary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BasicSalary")
                        .HasColumnType("REAL");

                    b.Property<double>("EmployeePensionContribution")
                        .HasColumnType("REAL");

                    b.Property<double>("EmployerPensionContribution")
                        .HasColumnType("REAL");

                    b.Property<double>("GrossSalary")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalPAYETax")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Salaries");
                });

            modelBuilder.Entity("SalaryCalculator.Infrastructure.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
